### ISSUE TITLE
Some tests are broken on Net 461 (culture-dependent thing)

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/BenchmarkDotNet#1039]
master branch, VS 2017 15.9.6, target net461, current UI culture is 'ru-RU'

Some tests are failing under both VS & Resharper test runners, first few of them:

* Tests 
  AllSetupAndCleanupMethodRunsAsyncGenericValueTaskSetupTest, 
  AllSetupAndCleanupMethodRunsAsyncValueTaskSetupTest 
  AnArrayCanBePassedToBenchmarkAsSpan
  ArgumentsArePassedToBenchmarks
  TaskReturningMethodsAreAwaited
  UserCanSpecifyCustomBuildConfiguration

  benchmark build fails with message
  ```
  error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  ```

* Tests  `WhenInvalidCommandLineArgumentIsPassedAnErrorMessageIsDisplayedAndNoBenchmarksAreExecuted` 
  `UnknownConfigMeansFailure`

  fail with ArgumentNullException.

*  Test CanDisassembleInlinableBenchmarks, error 'Assert.Contains() Failure
 Not found: (filter expression)'

*  Tests from LocalCoreClrToolchainTests, LocalCoreRtToolchainTests
 error 'System.IO.DirectoryNotFoundException : C:\Projects\corert\bin\Windows_NT.x64.Release provided as newIlcPath does NOT exist'

etc

**Comment by adamsitnik** [comment]
Could you please perform a full clean (`git clean -xfd` for example) and try to re-run?

It passes on AppVeyor and Azure DevOps, so an old bin is my first guess.

**Comment by ig-sinicyn** [comment]
Just a minute, will try.

**Comment by ig-sinicyn** [comment]
OK, I've made PR for culture-related part of the issue.

Some tests still failing when code is built as debug (`CanDisassembleInlinableBenchmarks` as example).

**Comment by adamsitnik** [comment]
Fixed by #1042

**Comment by ig-sinicyn** [comment]
@adamsitnik some tests still fail for debug builds, CanDisassembleInlinableBenchmarks as example. Is it ok?

**Comment by adamsitnik** [comment]
@ig-sinicyn in BDN we always do everything in Release, so honestly, I am not worried about the Debug builds. If you would like to make it work in Debug I would be very happy to review the PR :d
