### ISSUE TITLE
--exporters option *appears* not to be working

### ISSUE THREAD

**Issue by jskeet** [dotnet/BenchmarkDotNet#189]
Hooray - the NodaTime benchmarks run :)

Hooray - running with `--help` shows me the `json` exporter (thanks Matt!)

Boo - I don't actually get any JSON...

Running with:

``` text
dotnet run -- --exporters json ZonedDateTimePatternBenchmarks
```

or

``` text
dotnet run -- ZonedDateTimePatternBenchmarks --exporters json 
```

... my `BenchmarkDotNet.Artifacts\results` directory still contains csv, md and html, none of which I want, but no JSON :(

**Comment by mattwarren** [comment]
Sorry, I haven't documented it and we probably don't have the most intuitive mechanism

Not at my laptop to double check, but I'm pretty sure that 

  "exporter=Json"

should work

**Comment by mattwarren** [comment]
Whoops meant to type "exporter=json", although I think it's case insensitive (and if it isn't I'll fix it)

**Comment by jskeet** [comment]
I tried that:

```text
dotnet run -- --exporter=json *
```

Output:

```text
Unhandled Exception: System.InvalidOperationException: "--exporter" (from "--exporter=json") is an unrecognised Option
   at BenchmarkDotNet.Configs.ConfigParser.Parse(String[] args)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunBenchmarks(String[] args)
   at NodaTime.Benchmarks.Program.Main(String[] args) in c:\Users\Jon\Test\Projects\nodatime\src\NodaTime.Benchmarks\Program.cs:line 17
```

There's basically the same error when I use `--exporters=json`, which is the name that matches the help text:

BenchmarkDotNet v0.9.6
Options:
  --jobs <JOBS>                  Allowed values: default, legacyjitx86, legacyjitx64, ryujitx64, dry, alljits, clr, mono, longrun
  --columns <COLUMNS>            Allowed values: mean, stderror, stddev, operationpersecond, min, q1, median, q3, max, allstatistics, place
  --exporters <EXPORTERS>        Allowed values: csv, csvmeasurements, html, markdown, stackoverflow, github, plain, rplot, json
  --diagnosers <DIAGNOSERS>      Allowed values:
  --analysers <ANALYSERS>        Allowed values: environment
  --validators <VALIDATORS>      Allowed values: baseline, jitOptimizations, jitOptimizationsFailOnError
  --loggers <LOGGERS>            Allowed values:
```

The way the help is written, I'd really expect `--exporters json` to work...

**Comment by mattwarren** [comment]
Sigh, you're right, "--exporters=json" should also work, I'll fix that

At the moment only "exporters=json" works (without dashes)

I think you're the first person to use this, so you are finding all the bugs :)

**Comment by jskeet** [comment]
Not a problem :) Just tried it, and yes - I have json! (Along with the csv/html/md - shouldn't specifying the exporters effectively replace the default list?)

So yes, `exporters=json` works. Is `--exporters json` (space, not equals) meant to work? If not, we should change the help to include the `=`.

**Comment by jskeet** [comment]
(I note the JSON output is all on one line, btw. Maybe we should have different exporter names of json and formatted-json, where the only difference is whether or not it's formatted. The formatting would be great for readability, but obviously make the file much, much bigger.)

**Comment by mattwarren** [comment]
> Along with the csv/html/md - shouldn't specifying the exporters effectively replace the default list?

That's a good point, although if  we don't include certain "core" items (e.g. `ConsoleLogger`) users will get little or no output, which could be confusing.

But maybe we should be a bit more intelligent, i.e. if you specify `exporters=`, we *only* use the exporters you pass in, but leave `loggers`, `columns` set to the defaults?

**Comment by mattwarren** [comment]
With regards to the cmd line, which of these do you think should work or should they all work?

1. `--exporters=json`
1. `exporters=json`
1. `exporters json`

Are there any other that should also have the same effect? 

Remember we allow multiple options, such as `exporters=json,csv,markdown` so making the `=` required makes things easier (from the parsing POV).

**Comment by mattwarren** [comment]
> I note the JSON output is all on one line, btw. Maybe we should have different exporter names of json and formatted-json, where the only difference is whether or not it's formatted. The formatting would be great for readability, but obviously make the file much, much bigger.

I thought that when I wrote the Json export, but now you've also said the same thing I'll actually implement it! I'll also go with your names, i.e. `json` and `formatted-json`.

**Comment by jskeet** [comment]
Exactly. Any option specified should replace defaults; any option unspecified still uses the default.

**Comment by mattwarren** [comment]
You can now do:

- `exporter=json` => all results/measurements, no indentation (single-line)
- `exporter=formatted` => all results/measurements, with indentation (multi-line)
- `exporter=brief` => only results, no measurements, with indentation (multi-line)

**Comment by AndreyAkinshin** [comment]
@mattwarren, what is the current status of the issue? Can we mark it as a `fixed-in-develop`?

**Comment by mattwarren** [comment]
> what is the current status of the issue? Can we mark it as a fixed-in-develop?

Yeah that can be done. I'll open a more specific issue to address the problems/enhancements covered in [this comment](https://github.com/PerfDotNet/BenchmarkDotNet/issues/189#issuecomment-221607948) and [this one](https://github.com/PerfDotNet/BenchmarkDotNet/issues/189#issuecomment-221609718)

**Comment by AndreyAkinshin** [comment]
Am I right that this fix is a part of `0.9.8`?

**Comment by mattwarren** [comment]
Yeah, the main issue that @jskeet reported was fixed by 83fd20c79bbdbe456a34b5474be729b2e4ef5a54

**Comment by jskeet** [comment]
Just trying this now with 0.9.8, it isn't really fixed. You still need `--exporters=json` rather than `--exporters json` despite the `--help` option shows:

```
Options:
  --jobs <JOBS>               : Allowed values: default, legacyjitx86, legacyjitx64, ryujitx64, dry, alljits, clr,
                              :                 mono, longrun
  --columns <COLUMNS>         : Allowed values: mean, stderror, stddev, operationpersecond, min, q1, median, q3, max,
                              :                 allstatistics, place
  --exporters <EXPORTERS>     : Allowed values: csv, csvmeasurements, html, markdown, stackoverflow, github, plain,
                              :                 rplot, json, briefjson, formattedjson, asciidoc
```

(It's also not clear why I still get github, csv and html when I've only asked for briefjson... I think if the user specifies any exporters, those are the *only* ones that should be used.)

The tests in 83fd20c79bbdbe456a34b5474be729b2e4ef5a54 have `// Allow both "--arg=<value>" and "arg=<value>" (i.e. with and without the double dashes)` - but that's not the same as allowing `--arg value`.

**Comment by mattwarren** [comment]
@jskeet sorry about that, I'll take another look. 

What's the most common pattern for cmd-line args, is it `--arg value`, I know that's what the `dotnet` tooling uses, i.e:

```
λ dotnet build --help
.NET Builder

Usage: dotnet build [arguments] [options]

Arguments:
  <PROJECT>  The project to compile, defaults to the current directory. Can be one or multiple paths to project.json, project directory or globbing patter that matches project.json files

Options:
  -h|--help                           Show help information
  -o|--output <OUTPUT_DIR>            Directory in which to place outputs
  -b|--build-base-path <OUTPUT_DIR>   Directory in which to place temporary outputs
  -f|--framework <FRAMEWORK>          Compile a specific framework
  -r|--runtime <RUNTIME_IDENTIFIER>   Produce runtime-specific assets for the specified runtime
  -c|--configuration <CONFIGURATION>  Configuration under which to build
  --version-suffix <VERSION_SUFFIX>   Defines what `*` should be replaced with in version field in project.json
  --build-profile                     Set this flag to print the incremental safety checks that prevent incremental compilation
  --no-incremental                    Set this flag to turn off incremental build
  --no-dependencies                   Set this flag to ignore project to project references and only build the root project
```
