### ISSUE TITLE
Grand renaming

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/BenchmarkDotNet#787]
Since, we are going to introduce a lot of breaking changes in v0.11.0, it would be nice to rename a few things as well. =)
Current naming scheme has an important problem: we use the same generic words like "Benchmark", "Main", "Target" in different places for different purposes.
Thus, you can't say what "Target" means without a context.
This grand renaming has two main goals:

* Use one term for one purpose. We shouldn't reuse words for different things.
* Avoid "generic" words with unclear meaning if possible.

Here is my list of renaming:

### IterationMode

I suggest to split `IterationMode` to `IterationMode` and `IterationStage` as follows:

- [x] `Iteration`
  * `Mode`: `Idle`, `Workload`
  * `Stage`: `Jitting`, `Pilot`, `Warmup`, `General`, `Result`

Thus, we can use the `Workload` term for our the benchmark which we want to benchmark (no more `Main`, `Target`, `Method`, etc.)

### Benchmark

- [x] `Benchmark` -> `BenchmarkCase` (solving a conflict between `class Benchmark` and `class BenchmarkAttribute` which is used as `[Benchmark]`)
- [x] `Benchmark.Target` -> `BenchmarkCase.Descriptor`

Descriptor should include the following properties:

- [x] `Type`
- [x] `GlobalSetupMethod`, `GlobalCleanupMethod`, `IterationSetupMethod`, `IterationCleanupMethod`
- [x] `WorkloadMethod`

### Other renames

- [x] ~`Analyser` -> `Inspector` (solving a conflict between American "Analyser" and British "Analyzer")~,
  `Conclusion` -> `Inspection` (consistency)
- [x] `OrderProvider` -> `Orderer` (prefer one-word term)
- [x] ~`SummaryStyle` -> `Styler` (prefer one-word term)~
- [x] `IsBaseline` -> `Baseline` (consistency)
- [x] Move `EnvironmentVariables` from `InfrastructureMode` to `EnvMode`
- [x] `General` -> `Actual`

**Comment by AndreyAkinshin** [comment]
@adamsitnik, what do you think?

**Comment by adamsitnik** [comment]
> I suggest to split IterationMode to IterationMode and IterationStage as follows:

The only suggestion I have now is to rename `Idle` to `Overhead` 

> Benchmark -> BenchmarkCase
> Benchmark.Target -> BenchmarkCase.Descriptor
> OrderProvider -> Orderer

👍 

> Analyser -> Inspector 
> SummaryStyle -> Styler

I am not sure about these two, honestly, they don't sound better to me. @mattwarren do you have some better idea?

> BenchmarkAttribute.Baseline -> BenchmarkAttribute.IsBaseline (consistency with IsBaselineColumn and Job.Meta.IsBaseline)

I think that a lot of our users use `Baseline` for `[Benchmark]` and to cause less damage, I would rename the other two, less popular `IsBaseline` to `Baseline`

> Move EnvironmentVariables from InfrastructureMode to EnvMode

👍 but I would also rename `EnvMode` to `EnvironmentMode` to have full consistency. Since most of our users use only the fluent extension methods, the change should be transparent to them

**Comment by AndreyAkinshin** [comment]
> I am not sure about these two, honestly, they don't sound better to me.

@adamsitnik, and what do you think about "Analy**s**er" -> "Analy**z**er" (British -> American).

> I think that a lot of our users use Baseline for [Benchmark] and to cause less damage, I would rename the other two, less popular IsBaseline to Baseline

We can keep `[Benchmark(Baseline  true)]` and mark it as obsolete. The backward compatibility is important, but I want to introduce the best possible API in `v1.0` (after that, it will be hard to change the naming).

>  but I would also rename EnvMode to EnvironmentMode to have full consistency. Since most of our users use only the fluent extension methods, the change should be transparent to them

LGTM

**Comment by adamsitnik** [comment]
> and what do you think about "Analyser" -> "Analyzer" (British -> American).

To me it's ok, I prefer British option but I see the value of unification. And most probably very few users wrote their own analyzers so we are not going to break anybody.

> We can keep [Benchmark(Baseline true)] and mark it as obsolete.

I would prefer to keep it just "Baseline" but the idea with having both + obsolete is ok.

@AndreyAkinshin  Btw I saw your huge rename commits. It would be impossible without Resharper to do that!

**Comment by adamsitnik** [comment]
@AndreyAkinshin I have hit an issue after you recent renaming, but I have just pushed a fix for it.

Long story short: when we export job settings to `.cs` file : `job.XMode.YProperty` we expect that `XMode.YCharacteristic` exists, there was a mismatch between `MaxWorkloadIterationCountCharacteristic` and `MaxTargetIterationCount`.

I was not sure which name to use so I decided to simplify it: I have renamed `TargetCount` to `IterationCount`. I believe that this is more intuitive name, and I hope that you are going to like it too ;)

**Comment by AndreyAkinshin** [comment]
I'm still not happy about the latest version of naming. Currently, we have the following IterationStages: `Jitting`, `Pilot`, `Warmup`, `General` (former `Main`), `Result`. First of all, I don't like `General`, it would be nice to fine a better term.
A user can customize the amount of `Warmup` *Iterations* and `General` *Iterations*. The corresponding job properties are `WarmupCount` and `IterationCount`. It looks inconsistent to me.
Any ideas?

**Comment by adamsitnik** [comment]
Honestly I would call it like this:

```log
OverheadJitting
BenchmarkJitting

OverheadWarmup

BenchmarkPilot

BenchmarkWarmup

BenchmarkRun

BenchmarkResult
```

@AndreyAkinshin what do you think? or maybe we could ask our users on Twitter or sth?

**Comment by AndreyAkinshin** [comment]
`Benchmark` is a too generic term which we use everywhere. The "benchmark" term can include setup/cleanup, parameters, configuration, and so on. In the new terminology, we use the `Workload` term which corresponds to a single method without setup/cleanup and other stuff. I like it because it's hard to confuse it with anything.
Meanwhile, `Main`/`General`/`Run` are too generic words. If I see `BenchmarkRun` somewhere in the source code, what does it mean? Maybe it's the whole run session inside BenchmarkRunner? Or maybe it corresponds to `BenchmarkDotNet.Engines.RunResults` which contain information about overhead and workload runs? Or maybe it relates to `RunStrategy`? I can't say without reading the code.
I want to introduce one term which will be used for only one thing (`Main`/`General`/`Run` iterations), it should prevent any misunderstandings.

**Comment by Zhentar** [comment]
If I understand correctly, the defining feature of "Main"/"General" is that it is the one that is actually measured to produce the numbers in the results, so why not call it `Measurement`?

It's also not clear to me what `Result`  means... I would presume it to be calculation and/or analysis, but that seems like something that would only run once per test case, rather than once for every measurement iteration.

**Comment by AndreyAkinshin** [comment]
> If I understand correctly, the defining feature of "Main"/"General" is that it is the one that is actually measured to produce the numbers in the results, so why not call it Measurement?

Well, we already have the `Measurement` class which corresponds to any kind of measurements including Pilot, Warmup, and so on. It's also an important information. E.g., sometimes I want to verify that everything is OK with warmup and I need all warmup measurements for it. Thus, `Measurements` is also not the best term for that.

> It's also not clear to me what Result means... I would presume it to be calculation and/or analysis, but that seems like something that would only run once per test case, rather than once for every measurement iteration.

`Results` measurements are measurements which are used in the summary table. Basically, they are "Main"/"General" iterations with subtracted overhead with removed outliers.

**Comment by AndreyAkinshin** [comment]
I have another renaming idea.
For "Main"/"General" iterations, it's important to highlight that we are talking about real measurements without any calculation. My suggestion: `Natural`.
For "Result" iterations, it's important to highlight that we are talking about "fake" measurements with some postprocessing. My suggestions: `Effective`.

@adamsitnik what do you think?

**Comment by AndreyAkinshin** [comment]
@adamsitnik ?

**Comment by adamsitnik** [comment]
@AndreyAkinshin sorry for the very late reply, I just don't have any very good idea to share

I see your point with using the `Benchmark` word, I am fine with `Workload`.

Today we have:
```
OverheadJitting 
WorkloadJitting 

WorkloadPilot   

OverheadWarmup  
OverheadGeneral 

WorkloadWarmup  
WorkloadGeneral 
WorkloadResult  
```

What I would do would be a little simplification:

1. OverheadGeneral  -> Overhead
2. WorkloadGeneral  -> Workload
3. WorkloadResult  -> Result


And maybe one rename:  `WorkloadPilot  => PilotExperiment`

**Comment by AndreyAkinshin** [comment]
@adamsitnik, currently we have the following enums:
```cs
public enum IterationStage
{
    Jitting, Pilot, Warmup, General, Result, Unknown
}
public enum IterationMode
{
    Overhead, Workload, Unknown
}
```
I want to keep these two enums because it really simplifies the source code and it is more logical. We can discuss a simplification of the console output, but we still need a better name of `IterationStage.General` in the source code.

**Comment by adamsitnik** [comment]
@AndreyAkinshin So maybe `ActualRun` instead of `General`?

> I want to keep these two enums because it really simplifies the source code and it is more logical. We can discuss a simplification of the console output, but we still need a better name of IterationStage.General in the source code.

👍 

We should be very specific in the code and easy to understand in the console output.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, `Actual` looks good to me.
